-- 1. Table des profils utilisateurs (liée à auth.users)
create table public.profiles (
  id uuid references auth.users on delete cascade not null primary key,
  email text,
  full_name text,
  role text check (role in ('admin', 'pharmacist', 'patient')),
  pharmacy_id bigint, -- Sera lié plus tard si c'est un pharmacien
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. Table des pharmacies
create table public.pharmacies (
  id bigint generated by default as identity primary key,
  name text not null,
  quartier text,
  lat double precision,
  lng double precision,
  phone text,
  is_on_duty boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 3. Table des produits (Médicaments)
create table public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  description text,
  image_url text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 4. Table des stocks (Lien Pharmacie <-> Produit)
create table public.stocks (
  id bigint generated by default as identity primary key,
  pharmacy_id bigint references public.pharmacies(id) on delete cascade not null,
  product_id bigint references public.products(id) on delete cascade not null,
  price integer not null,
  available boolean default true,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 5. Sécurité (Row Level Security)
alter table public.profiles enable row level security;
alter table public.pharmacies enable row level security;
alter table public.products enable row level security;
alter table public.stocks enable row level security;

-- Politiques simples pour le MVP (Tout le monde peut lire, mais modification restreinte)
create policy "Public profiles are viewable by everyone." on public.profiles for select using (true);
create policy "Users can insert their own profile." on public.profiles for insert with check (auth.uid() = id);

create policy "Pharmacies are viewable by everyone." on public.pharmacies for select using (true);
create policy "Products are viewable by everyone." on public.products for select using (true);
create policy "Stocks are viewable by everyone." on public.stocks for select using (true);

-- Données de test (Seed)
insert into public.products (name) values 
('Doliprane 1000mg'), 
('Doliprane 500mg'), 
('Coartem 80/480'), 
('Paracétamol'), 
('Efferalgan');

insert into public.pharmacies (name, quartier, lat, lng, is_on_duty, phone) values
('Pharmacie de la Gare', 'Gare, Cotonou', 6.3654, 2.4183, true, '+229 21 31 00 00'),
('Pharmacie Camp Guezo', 'Camp Guezo, Cotonou', 6.3550, 2.4250, false, '+229 21 30 15 15'),
('Pharmacie Saint Michel', 'Saint Michel, Cotonou', 6.3700, 2.4300, true, '+229 21 32 22 22');

-- Stocks initiaux
insert into public.stocks (pharmacy_id, product_id, price, available) values
(1, 1, 1500, true), -- Pharma 1 a du Doliprane 1000
(1, 3, 2500, true), -- Pharma 1 a du Coartem
(2, 1, 1550, true), -- Pharma 2 a du Doliprane 1000
(3, 2, 800, true);  -- Pharma 3 a du Doliprane 500
